from .bot_names import ARCHI_LICH
from .bot_names import ARCHI_PALADIN_MORTIUS
from .bot_names import FOREST_KEEPER
from .bot_names import GROMLECH_BANDIT
from .bot_names import GROMLECH_BLUETOOTH
from .bot_names import GROMLECH_WIZARD
from .bot_names import HELPER_OF_ATAMAN
from .bot_names import KHALGHAN_RAIDER
from .bot_names import LICH
from .bot_names import MINION_OF_LOKAR
from .bot_names import PALADIN_MORTIUS
from .bot_names import PLAGUE_ZOMBIE
from .bot_names import RENEGADE_DRUID
