from .local_config import NICKNAME
from .local_config import SIEGE
from .local_config import PERSON_ROLE
from .local_config import LEADER_TYPE
from .local_config import LEADER_NAME
from .local_config import MAG_KILLER
from .local_config import PERSON_TYPE
from .local_config import PARTY_MEMBERS
from .local_config import MAG_DAMAGER
from .local_config import DEAD_PLAGUE_ZOMBIE
from .local_config import LEN_PARTY
from .local_config import CHECKER_IP_SITE
from .local_config import FIGHT_ITERATIONS
from .local_config import SLEEP_TIME
from .local_config import SLEEP_TIME_PER_HIT
from .local_config import FIGHT_TEST_MODE
from .local_config import AUTO_BUFF
from .local_config import AB
from .local_config import LOGIN
from .local_config import PASSWORD
from .local_config import NICKNAME
from .local_config import PROXY
from .local_config import PROXY_IP
from .local_config import PROXY_LOG
from .local_config import PROXY_PASS
from .local_config import PROXY_PORT
from .local_config import CITY
from .local_config import TELEPORT_CITY
from .local_config import CHANNEL_ID
from .local_config import CHANNEL_ID_FRIENDS
from .local_config import CHANNEL_ID_ROMANSON
from .local_config import CHANNEL_ID_HUNTER
from .local_config import CHANNEL_ID_TURNOFF
from .local_config import CHANNEL_ID_ANGEL
from .local_config import CHANNEL_ID_DICT
from .local_config import CHANNEL_ID_LEADER
from .local_config import TG_TOKEN
from .local_config import HEADER
from .local_config import DATA
from .local_config import PROXIES

from .urls import URL
from .urls import URL_GAME
from .urls import URL_MAIN
from .urls import URL_EVENT
from .urls import URL_KEEP_CONNECTION
from .urls import URL_PLAYER_INFO
from .urls import URL_SCROLLS_INV

from .variable_names import SOLO
from .variable_names import SLAVE
from .variable_names import LEADER
from .variable_names import MAG
from .variable_names import WARRIOR
from .variable_names import HUNTER
from .variable_names import ROMANSON
from .variable_names import TURNOFF
from .variable_names import ANGEL

from .pattern import FIND_WEAPON_SCROLL_PART_1
from .pattern import FIND_WEAPON_SCROLL_PART_2
from .pattern import FIND_DEAD_HIT
from .pattern import FIND_USE
from .pattern import FIND_MAPBT
from .pattern import FIND_PARAM_OW
from .pattern import FIND_FEXP
from .pattern import FIND_STATS
from .pattern import FIND_POS_VARS
from .pattern import FIND_POS_MANA
from .pattern import FIND_POS_TYPE
from .pattern import FIND_POS_OCHD
from .pattern import FIND_OBJ_ACTION
from .pattern import FIND_VAR_OBJ_ACTION
from .pattern import FIND_FRAME
from .pattern import FIND_IMP_PAST
from .pattern import FIND_TELEPORT
from .pattern import FIND_SCROLL_STRIKE_FURY
from .pattern import FIND_PAGE_INVENTORY
from .pattern import FIND_IN_CITY
from .pattern import FIND_FROM_NATURE_TO_INV
from .pattern import FIND_INSHP
from .pattern import FIND_FIRST_PART
from .pattern import FIND_SECOND_PART
from .pattern import FIND_STRING_WITH_QUERY
from .pattern import FIND_EFFECTS_INFO_PATTERN
from .pattern import FIND_VAR_EFF
from .pattern import FIND_LIVES_G2
from .pattern import FIND_FIGHT_VARIABLES_PART1
from .pattern import FIND_FIGHT_VARIABLES_PART2
from .pattern import DISABLED
from .pattern import TEXT2
from .pattern import SLOTS
