from .buffs_name import AIR_BARRIER
from .buffs_name import BOUNTY_OF_LIGHTNING
from .buffs_name import FIRE_SHIELD
from .buffs_name import FLAMING_RACK
from .buffs_name import HEADWIND
from .buffs_name import IFRITS_CURSE
from .buffs_name import INCREDIBLE_ACCURACY
from .buffs_name import METEOR_SHIELD
from .buffs_name import POISONING
from .buffs_name import POWER
from .buffs_name import PUSH
from .buffs_name import QUICKSAND
from .buffs_name import SAND_WALL
from .buffs_name import SOURCE
from .buffs_name import STONE_FLESH
from .buffs_name import VULNERABLE_TO_FIRE
